# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-11 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='rec/media/%m%d')),
                ('size', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('point', models.CharField(max_length=64)),
                ('duration', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('point', models.CharField(max_length=64)),
                ('createTime', models.CharField(max_length=128)),
                ('count', models.ImageField(null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='rec/picture/%m%d')),
                ('size', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('point', models.CharField(max_length=64)),
                ('date', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='app.PhotoAlbum')),
            ],
        ),
    ]
